### ISSUE TITLE
Release akka-http-play-json 1.11.0 for Scala 2.11

### ISSUE THREAD

**Issue by samueltardieu** [hseeberger/akka-http-json#109]
akka-http 10.0.0 supports Scala 2.11. akka-http-play-json 1.11.0 should be released for Scala 2.11 so that people can upgrade akka-http without getting an eviction warning.

**Comment by hseeberger** [comment]
play-json will only be added once it supports Scala 2.12.

**Comment by Korbik** [comment]
I'm sorry, I don't get why there is no Scala 2.11 1.11.0 release.
I'm using the latest version of akka (2.4.17) and akka-http (10.0.3) for Scala 2.11 
I would have use the Scala 2.11 version of 1.12.0 but I can't because it pulls play 2.6 and I need to stay on play 2.5 for now.

Could you please publish akka-http-play-json 1.11.0 for Scala 2.11 or give more details about your reasons ?

**Comment by hseeberger** [comment]
akka-http-json is built against 2.12 (and 2.11) since 1.11, hence it can only support JSON libs which support 2.12. 

Why do you not use (stick with) 1.10?

**Comment by Korbik** [comment]
I wanted to upgrade to the current version 1.10.1 because of the dependency with akka-http-experimental. 

I completely understand the need to have the support for 2.12 from the JSON libs but then I would expect the version 1.11.0 available for 2.11 but not 2.12 since the play dependency (2.5).
