### ISSUE TITLE
Mixing circe routes together with other formField routes seems to break the latter

### ISSUE THREAD

**Issue by silvaren** [hseeberger/akka-http-json#148]
Hi guys, maybe I'm missing something so I'd like to confirm it's actually a bug. If I modify the [example app from the repo](https://github.com/hseeberger/akka-http-json/blob/master/akka-http-circe/src/test/scala/de/heikoseeberger/akkahttpcirce/ExampleApp.scala), changing the routes like below to include a formField route:

```
  private def route(implicit mat: Materializer) = {
    import Directives._
    import de.heikoseeberger.akkahttpcirce.FailFastCirceSupport._
    import io.circe.generic.auto._

    pathSingleSlash {
      post {
        entity(as[Foo]) { foo =>
          complete {
            foo
          }
        }
      }
    } ~
      path("formurlencoded") {
        post {
          formFields('coolKey) { coolKey =>
            complete(s"The cool value is '${coolKey}'")
          }
        }
      }
  }
```
If I run and test it with the added route:
`curl -d "coolKey=coolValue" -X POST http://localhost:8000/formurlencoded`

I get the following error:
`The request's Content-Type is not supported. Expected: application/json or multipart/form-data`

But if I remove all circe/json related code like in the following:

```
  private def route(implicit mat: Materializer) = {
    import Directives._
//    import de.heikoseeberger.akkahttpcirce.FailFastCirceSupport._
//    import io.circe.generic.auto._
//
    pathSingleSlash {
      post {
          complete {
            "no json :("
          }
      }
    } ~
      path("formurlencoded") {
        post {
          formFields('coolKey) { coolKey =>
            complete(s"The cool value is '${coolKey}'")
          }
        }
      }
  }
```

And test it again with:
`curl -d "coolKey=coolValue" -X POST http://localhost:8000/formurlencoded`

I get the expected response:
`The cool value is 'coolValue'`

Does this look like a bug to you or am I missing something?

Thanks

**Comment by hseeberger** [comment]
Hmm ... interesting! That might be a bug in Akka HTTP (not here).

Have you tried to move the import of `FailFastCirceSupport._` to the first sub-route, i.e. limit its scope?

**Comment by silvaren** [comment]
Yes, it does work when moving the import to the first sub-route, as in:

```
  private def route(implicit mat: Materializer) = {
    import Directives._
    import io.circe.generic.auto._

    pathSingleSlash {
      post {
        import de.heikoseeberger.akkahttpcirce.FailFastCirceSupport._
        entity(as[Foo]) { foo =>
          complete {
            foo
          }
        }
      }
    } ~
      path("formurlencoded") {
        post {
          formFields('coolKey) { coolKey =>
            complete(s"The cool value is '${coolKey}'")
          }
        }
      }
  }
```

Do you think it is a bug on Akka HTTP then?

**Comment by hseeberger** [comment]
I think so, because I don't understand why adding JSON support into the scope should change the accepted content type. In your example above, when you don't add any JSON support, it seems that the not sending a content type (multipart/form-data) is accepted. Why? And why not if you add JSON support?

**Comment by silvaren** [comment]
[Found a similar issue on Akka HTTP repo.](https://github.com/akka/akka-http/issues/541) related to unmarshallers instead of specific to JSON. Hopefully someone can bring light to the issue.

**Comment by jrudolph** [comment]
I haven't checked this exact case but it seems that the circe support provides an implicit unmarshaller which is too generic to be imported in user code.

In this case, the problem is probably [this implicit](https://github.com/hseeberger/akka-http-json/blob/master/akka-http-circe/src/main/scala/de/heikoseeberger/akkahttpcirce/CirceSupport.scala#L118):

```scala
implicit def unmarshaller[A: Decoder]: FromEntityUnmarshaller[A]
```

if circe is able to provide a `Decoder[A]` for any type `A`. Importing this implicit unmarshaller somewhere is equal to claiming that you know that every `A` should be unmarshalled from json which is often not what you want. It will interfere not only with `formField` but every single other implicit unmarshaller in Akka Http routes.

That said, I think that the particular case with `formField` can be improved in akka-http itself as well.

**Comment by hseeberger** [comment]
Hmm ... not sure I fully understand:

First, the mentioned unmarshaller is only available for types `A` which have a `Decoder`. Second, I think akka-http does the exact same thing here:

``` scala
implicit def sprayJsonUnmarshaller[T](implicit reader: RootJsonReader[T]): FromEntityUnmarshaller[T]
```

**Comment by hseeberger** [comment]
@jrudolph ?

**Comment by rabzu** [comment]
Same thing happens when using PlayJsonSupport. But it seems to be akka-http bug

**Comment by cwei-bgl** [comment]
Hi, I am getting exactly the same issue. I can resolve it by limiting the import scope of 'de.heikoseeberger.akkahttpcirce.FailFastCirceSupport._'. Is there any progress on this?

**Comment by hseeberger** [comment]
It's an Akka HTTP issue. Not related to this project.
